# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      #day: "saturday"
      #time: "14:00"
      #timezone: Europe/Rome
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "php dependency"
    groups:
      pagerfanta:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "babdev/pagerfanta-bundle"
          - "pagerfanta/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "doctrine/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "ecotone/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "league/oauth2-server-bundle"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]


  ########################################################################################################################
  #
  #   Tools dependencies
  #
  ########################################################################################################################
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/ecs"
    versioning-strategy: "increase"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "Tools - ecs "
    labels:
      - "Tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/psalm"
    versioning-strategy: "increase"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "Tools - psalm "
    labels:
      - "Tool dependency"
    groups:
      psalm:
        applies-to: "version-updates"
        dependency-type: "development"
        patterns:
          - "vimeo/*"
          - "psalm/plugin-*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/rector"
    versioning-strategy: "increase"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "Tools - rector "
    labels:
      - "Tool dependency"


  ########################################################################################################################
  #
  #   Github Actions dependencies
  #
  ########################################################################################################################
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    labels:
      - "GHA dependency"
