twig:
    file_name_pattern: '*.twig'

    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        release_version: '%release.version%'

when@test:
    twig:
        strict_variables: true
