twig:
    file_name_pattern: '*.twig'

    paths:
        # directories are relative to the project root dir (but you
        # can also use absolute directories)
        '_iam/src/Infrastructure/Templates': 'iam'

    form_themes:
        - 'bootstrap_5_layout.html.twig'

    globals:
        release_version: '%release.version%'
        is_user_registration_enabled: '%app.setting.is_user_registration_enabled%'
        is_user_password_recovery_enabled: '%app.setting.is_user_password_recovery_enabled%'

when@test:
    twig:
        strict_variables: true
