# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  notifier.setting.recipient.admin: 'teclaizerai@gmail.com'
  notifier.setting.recipient.system.email: 'system@auth.openemrmarketplace.com'
  notifier.setting.recipient.system.name: 'auth.openemr.com'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    bind:
      # Param for
      # AdapterForSendingEmail service
      $systemEmailAddress: '%notifier.setting.recipient.system.email%'
      $systemEmailName: '%notifier.setting.recipient.system.name%'


  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Notifier\:
    resource: '../../../../../context/notifier/src/'
    exclude:
        - '../../../../../context/notifier/src/Core/UserRecipient/'


  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

#  cache.notifier_clearer: '@cache.default_clearer'
#
#  cache.notifier:
#    parent: 'cache.adapter.filesystem'
#    public: true
#    tags:
#      - { name: 'cache.pool',  clearer: 'cache.notifier_clearer'  }
#  cache.notifier.taggable:
#    class: Symfony\Component\Cache\Adapter\TagAwareAdapter
#    arguments: ['cache.notifier']
#    tags:
#      - { name: 'cache.taggable', pool: 'cache.notifier' }
#
#  cache.adapter.filesystem.notifier:
#    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
#    abstract: true
#    public: false
#    arguments:
#      - ''
#      - 0
#      - '%kernel.cache_dir%/pools/notifier'
#      - '@cache.default_marshaller'
#    #calls:
#      #- 'setLogger'
#    tags:
#      - { name: 'cache.pool', {clearer: 'cache.default_clearer', reset: 'reset' }
#      #- { name: 'monolog', channel: 'cache'}


when@test:
  parameters:
    notifier.setting.recipient.admin: 'teclaizerai@gmail.com'
    notifier.setting.recipient.system.email: 'sys@auth.oe-modules.com'
    notifier.setting.recipient.system.name: 'auth.oe-modules.com'

  services:
    # default configuration for services in *this* file
    _defaults:
      autowire: true      # Automatically injects dependencies in your services.
      autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
      public: true

      bind:
        # Param for
        # AdapterForSendingEmail service
        $systemEmailAddress: '%notifier.setting.recipient.system.email%'
        $systemEmailName: '%notifier.setting.recipient.system.name%'


    #
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
      Notifier\:
          resource: '../../../../../context/notifier/src/'
          exclude:
              - '../../../../../context/notifier/src/Core/UserRecipient/'

