# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  notifier.setting.recipient.admin: 'teclaizerai@gmail.com'
  notifier.setting.recipient.system.email: 'system@auth.openemrmarketplace.com'
  notifier.setting.recipient.system.name: 'auth.openemr.com'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    bind:
      # Param for
      # AdapterForSendingEmail service
      $systemEmailAddress: '%notifier.setting.recipient.system.email%'
      $systemEmailName: '%notifier.setting.recipient.system.name%'


  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Notifier\:
    resource: '../../../../../context/notifier/src/'


  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
