controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

iam_controllers:
    resource:
        path: ../_iam/src/AdapterForWeb/
        namespace: IdentityAccess\AdapterForWeb
    type: attribute
