controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

iam_admin_index_controller:
    resource: IdentityAccess\AdapterForWeb\AdminIndexController
    type: attribute
#TODO: remove
iam_admin_com_controller:
    resource: IdentityAccess\AdapterForWeb\ExternalSystemCommunicationController
    type: attribute

iam_admin_account_controllers:
    resource:
        path: ../_iam/src/AdapterForWeb/Administration/Account/
        namespace: IdentityAccess\AdapterForWeb\Administration\Account
    type: attribute

iam_admin_oauth_client_controllers:
    resource:
        path: ../_iam/src/AdapterForWeb/Administration/OauthClient/
        namespace: IdentityAccess\AdapterForWeb\Administration\OauthClient
    type: attribute


api_auth_controllers:
    resource:
        path: ../_iam/src/AdapterForApi/Auth/
        namespace: IdentityAccess\AdapterForApi\Auth
    type: attribute
