name: Acceptance stage

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      triggering-sha:
        required: true
        type: string

env:
  # PHP SETTINGS
  PHP_EXTENSIONS: ctype, iconv, openssl
  PHP_EXTENSIONS_CACHE_KEY: cache-php-extensions-v3

jobs:
  acceptance-checks:
    name: Acceptance checks (php-${{ matrix.php }})
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    services:
      mysql:
        image: mariadb:10.6.20
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    strategy:
      matrix:
        php:
          - '8.2'
        is-php-experimental: [ false ]
        generate-coverage-report: [ false ]
      fail-fast: false
    steps:
      - name: Checkout on SHA-${{ inputs.triggering-sha }}
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.triggering-sha }}

      - name: Show CI job info (dump context)
        if: ${{ vars.SHOW_WORKFLOW_INFO == '1'}}
        uses: crazy-max/ghaction-dump-context@v2


      - name: info triggering workflow - commit message
        run: echo commit message from triggering workflow '${{ github.event.workflow_run.head_commit.message }}'

      - name: Setup PHP and composer dependencies
        uses: './.github/actions/php-setup'
        with:
            php-version: '8.2'
            php-extensions: ${{ env.PHP_EXTENSIONS }}
            extensions-cache-key:  ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
            use_php_extensions-cache: ${{ vars.USE_PHP_EXTENSION_CACHE }}
            use_composer-cache: ${{ vars.USE_COMPOSER_CACHE }}

      - name: Run database migrations
        if: ${{ github.ref_name == 'main' }}
        run: ./bin/console doctrine:migrations:migrate -e test -n -vv --allow-no-migration --ansi
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4

      - name: Show database migrations list
        if: ${{ github.ref_name == 'main' }}
        run: ./bin/console doctrine:migrations:list -e test --ansi
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4

      - name: Run database schema update
        if: ${{ github.ref_name != 'main' }}
        run: ./bin/console doctrine:schema:update -e test --force --ansi
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4

      - name: Run database schema validate
        run: ./bin/console doctrine:schema:validate -e test --ansi
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4


  integration-test:
    name: Integration tests (php-${{ matrix.php }})
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    services:
      mysql:
        image: mariadb:10.6.20
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    strategy:
      matrix:
        php:
          - '8.2'
        is-php-experimental: [ false ]
        generate-coverage-report: [ false ]
      fail-fast: false
    steps:
      - name: Checkout on SHA-${{ inputs.triggering-sha }}
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.triggering-sha }}

      - name: Show CI job info (dump context)
        if: ${{ vars.SHOW_WORKFLOW_INFO == '1'}}
        uses: crazy-max/ghaction-dump-context@v2

      - name: info triggering workflow - commit message
        run: echo commit message from triggering workflow '${{ github.event.workflow_run.head_commit.message }}'

      - name: Setup PHP and composer dependencies
        uses: './.github/actions/php-setup'
        with:
            php-version: '8.2'
            php-extensions: ${{ env.PHP_EXTENSIONS }}
            extensions-cache-key:  ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
            use_php_extensions-cache: ${{ vars.USE_PHP_EXTENSION_CACHE }}
            use_composer-cache: ${{ vars.USE_COMPOSER_CACHE }}

      - name: Run database migrations
        if: ${{ github.ref_name == 'main' }}
        run: ./bin/console doctrine:migrations:migrate -e test -n -vv --allow-no-migration --ansi
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4

      - name: Run database schema update
        if: ${{ github.ref_name != 'main' }}
        run: ./bin/console doctrine:schema:update -e test --force --ansi
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4

      - name: Run database schema validate
        run: ./bin/console doctrine:schema:validate -e test --ansi
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4

      - name: Run integration testsuite
        run: ./bin/phpunit --testsuite integration --colors=always
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4


  functional-test:
    name: Functional tests (php-${{ matrix.php }})
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    services:
      mysql:
        image: mariadb:10.6.16
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    strategy:
      matrix:
        php:
          - '8.2'
        is-php-experimental: [ false ]
        generate-coverage-report: [ false ]
      fail-fast: false
    steps:
      - name: Checkout on SHA-${{ inputs.triggering-sha }}
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.triggering-sha }}

      - name: Show CI job info (dump context)
        if: ${{ vars.SHOW_WORKFLOW_INFO == '1'}}
        uses: crazy-max/ghaction-dump-context@v2

      - name: info triggering workflow - commit message
        run: echo commit message from triggering workflow '${{ github.event.workflow_run.head_commit.message }}'

      - name: Setup PHP and composer dependencies
        uses: './.github/actions/php-setup'
        with:
            php-version: '8.2'
            php-extensions: ${{ env.PHP_EXTENSIONS }}
            extensions-cache-key:  ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
            use_php_extensions-cache: ${{ vars.USE_PHP_EXTENSION_CACHE }}
            use_composer-cache: ${{ vars.USE_COMPOSER_CACHE }}

      - name: Run database migrations
        if: ${{ github.ref_name == 'main' }}
        run: ./bin/console doctrine:migrations:migrate -e test -n -vv --allow-no-migration --ansi
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4

      - name: Run database schema update
        if: ${{ github.ref_name != 'main' }}
        run: ./bin/console doctrine:schema:update -e test --force --ansi
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4

      - name: Run database schema validate
        run: ./bin/console doctrine:schema:validate -e test --ansi
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4

      - name: Run functional testsuite
        run: ./bin/phpunit --testsuite functional --colors=always
        env:
          DATABASE_URL: mysql://test:test@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=10.6.20-MariaDB&charset=utf8mb4
